export default {
    isTimeout: jest.fn().mockReturnValue(false),
    onAllRepositoriesScanned: jest.fn(),
    onTaskStart: jest.fn(),
    onRepositoryRead: jest.fn(),
    onRepositoryClone: jest.fn(),
    onRepositoryPull: jest.fn(),
    onLintStart: jest.fn(),
    onFileLintEnd: jest.fn(),
    onFileLintSlow: jest.fn(),
    onLinterCrash: jest.fn(),
    onWorkerCrash: jest.fn(),
    onCloneFailure: jest.fn(),
    onPullFailure: jest.fn(),
    onReadFailure: jest.fn(),
    on: jest.fn(),
    off: jest.fn(),
    onWriteFailure: jest.fn(),
    onLintEnd: jest.fn(),
};
