module.exports = {
    /** Repositories to scan */
    repositories: [
        'ant-design/ant-design',
        'AriPerkkio/js-framework-playground',
        'oldboyxx/jira_clone',
        'mui-org/material-ui',
        'reach/reach-ui',
        'react-bootstrap/react-bootstrap',
        'StreakYC/react-smooth-collapse',
        'pmndrs/react-spring',
        'AriPerkkio/scrpr',
        'AriPerkkio/state-mgmt-examples',
        'AriPerkkio/suspense-examples',
        'withspectrum/spectrum',
        'codesandbox/codesandbox-client',
        'Automattic/wp-calypso',
        'vercel/next-site',
        'artsy/force',
        'reactjs/reactjs.org',
        'zesty-io/accounts-ui',
        'zesty-io/design-system',
        'segmentio/evergreen',
        'segmentio/ui-box',
        'kentcdodds/kentcdodds.com',
        'kentcdodds/react-fundamentals',
        'kentcdodds/testing-react-apps',
        'kentcdodds/react-suspense',
        'kentcdodds/react-hooks',
        'kentcdodds/react-performance',
        'kentcdodds/advanced-react-hooks',
        'kentcdodds/advanced-react-patterns',
        'kentcdodds/bookshelf',
        'kentcdodds/react-testing-library-examples',
        'kentcdodds/learn-react',
        'kentcdodds/react-testing-library-course',
        'kentcdodds/concurrent-react',
        'project-bobon/bobonroastprofile',
        'gothinkster/react-redux-realworld-example-app',
        '1ven/do',
        'dockunit/platform',
        'afghl/dribbble-demo',
        'DevAlien/dripr-ui',
        'ismaelgt/english-accents-map',
        'rwieruch/favesound-mobx',
        'rwieruch/favesound-redux',
        'feednext/feednext',
        'skidding/flatris',
        'limichange/flex-editor',
        'pearofducks/foodprocessor',
        'HVF/franchise',
        'getguesstimate/guesstimate-app',
        'vercel/hyper',
        'stevenhauser/i-have-to-return-some-videotapes',
        'skidding/illustrated-algorithms',
        'bebraw/invoice-frontend',
        'gpbl/isomorphic500',
        'WebbyLab/itsquiz-wall',
        'docker/kitematic',
        'KrateLabs/KrateLabs-App',
        'afghl/dribble-demo',
        'zeit/hyper',
        'koodilehto/invoice-frontend',
        'insin/lifequote',
        'paulhoughton/mortgage',
        'paulhoughton/mortgage-mobx',
        'browniefed/pdxlivebus',
        'Khan/perseus',
        'guyellis/plant',
        'benoitvallon/react-native-nw-react-calculator',
        'insin/react-hn',
        'LeoAJ/react-iTunes-search',
        'FormidableLabs/react-music',
        'echenley/react-news',
        'lkazberova/react-photo-feed',
        'afonsopacifer/react-pomodoro',
        'pl12133/react-solitaire',
        'chvin/react-tetris',
        'fcsonline/react-transmission',
        'web-pal/react-trello-board',
        'fullstackreact/react-yelp-clone',
        'SKempin/reactjs-tmdb-app',
        'hoppula/refire-forum',
        'antoinejaussoin/retro-board',
        'ritoplz/ritoplz',
        'andrewngu/sound-redux',
        'FormidableLabs/spectacle',
        'sprintly/sprintly-ui',
        'torontojs/torontojs.com',
        'captbaritone/winamp2-js',
        'marmelab/react-admin',
        'palantir/blueprint',
        'microsoft/fluentui',
        'reactstrap/reactstrap',
        'Semantic-Org/Semantic-UI-React',
        'grommet/grommet',
        'chakra-ui/chakra-ui',
        'rebassjs/rebass',
        'FortAwesome/react-fontawesome',
        'reakit/reakit',
        'rsuite/rsuite',
        'uber/baseweb',
        'primefaces/primereact',
        'couds/react-bulma-components',
        'kulakowka/react-bulma',
        'dfee/rbx',
        'fibo/trunx',
        'emortlock/tailwind-react-ui',
        'knipferrc/tails-ui',
        'geist-org/react',
        'elastic/eui',
        'brillout/awesome-react-components',
        'JedWatson/react-select',
        'atlassian/react-beautiful-dnd',
        'react-dnd/react-dnd',
        'strml/react-grid-layout',
        'tannerlinsley/react-table',
        'adazzle/react-data-grid',
        'mzabriskie/react-draggable',
        'bokuweb/react-resizable-and-movable',
        'strml/react-resizable',
        'bokuweb/react-resizable-box',
        'axmz/react-searchbox-awesome',
        'bokuweb/react-sortable-pane',
        'aeagle/react-spaces',
        'airbnb/react-dates',
        'intljusticemission/react-big-calendar',
        'Hacker0x01/react-datepicker',
        'orgsync/react-list',
        'yahoo/react-intl',
        'i18next/react-i18next',
        'davidtheclark/react-aria-modal',
        'greena13/react-hotkeys',
        'glortho/react-keydown',
        'gilbarbara/react-joyride',
        'bvaughn/react-virtualized',
        'bvaughn/react-window',
        'text-mask/text-mask',
        'dvtng/react-loading-skeleton',
        'KyleAMathews/react-spinkit',
        'airbnb/rheostat',
        'zpao/qrcode.react',
        'pierpo/react-archer',
        'phuoc-ng/react-pdf-viewer',
        'mkosir/react-parallax-tilt',
        'matteobruni/tsparticles',
        'rackt/react-autocomplete',
        'moroshko/react-autosuggest',
        'eliseumds/react-autocomplete',
        'prometheusresearch/react-autocomplete',
        'gragland/instatype',
        'paypal/downshift',
        'ericgio/react-bootstrap-typeahead',
        'facebook/react-art',
        'Flipboard/react-canvas',
        'pilwon/react-famous',
        'freiksenet/react-kinetic',
        'gorangajic/react-svg-morph',
        'kmkzt/react-hooks-svgdrawing',
        'chrvadala/react-svg-pan-zoom',
        'clintonwoo/hackernews-react-graphql',
        'reduction-admin/react-reduction',
        'jeffersonRibeiro/react-shopping-cart',
        'elastic/kibana',
        'firefox-devtools/debugger',
        'mattermost/mattermost-webapp',
        'gaearon/overreacted.io',
        'dnote/dnote',
    ],

    /** Extensions of files under scanning */
    extensions: ['js', 'jsx', 'ts', 'tsx'],

    /** Optional pattern used to exclude paths */
    pathIgnorePattern: `(${[
        'node_modules',
        '\\/\\.', // Any file or directory starting with dot, e.g. ".git"
        'test-results',
        'tests',
        'docs',
        '/dist/',
        '/build/',

        // Minified JS committed to remote
        'codesandbox-client/packages/app/static/js',
        'codesandbox-client/standalone-packages',
        'dockunit/platform/assets',
        'hyper/bin',
        'react-solitaire/lib/index\\.js',
        'babel\\.js',
        'chunk\\.js',
        'react-dom\\.development\\.js',
        'vendor\\.min\\.js',
        'jquery-3\\.4\\.1\\.min\\.js',
    ].join('|')})`,

    /** Rules used to filter out results */
    rulesUnderTesting: ['react/no-unstable-nested-components'],

    /** Optional syntax for the result parser. Valid values are plaintext, markdown. Defaults to markdown on CLI, plaintext on CI */
    resultParser: 'markdown',

    /** Maximum amount of tasks ran concurrently */
    concurrentTasks: 3,

    /** ESLint configuration */
    eslintrc: {
        root: true,
        env: {
            es6: true,
        },
        parserOptions: {
            ecmaVersion: 2020,
            sourceType: 'module',
            ecmaFeatures: {
                jsx: true,
            },
        },
        settings: {
            react: {
                version: '16.13.1',
            },
        },
        plugins: ['react'],
        rules: {
            'react/no-unstable-nested-components': ['error'],
        },
    },

    /** Optional boolean flag used to set CI mode. Ignored when process.env.CI is set. */
    CI: false,
};
