name: 'Setup-node and cache'
description: 'Base setup for each action'
author: 'AriPerkkio'
inputs:
    node-version:
        required: false
        description: 'Node version for setup-node'
        default: '20'
runs:
    using: 'composite'
    steps:
        - name: Install pnpm
          uses: pnpm/action-setup@v4

        - name: Set node version to ${{ inputs.node-version }}
          uses: actions/setup-node@v6
          with:
              node-version: ${{ inputs.node-version }}

        - name: Versions
          shell: bash
          run: |
              node --version
              npm --version
              pnpm --version
