name: 'Smoke test'
description: 'Base setup for each smoke test action'
author: 'AriPerkkio'
inputs:
    config:
        required: true
        description: 'Name of the plugin configuration'
runs:
    using: 'composite'
    steps:
        - uses: ./.github/actions/setup-and-cache

        - name: Install & build eslint-remote-tester
          run: |
              pnpm install
              pnpm build
          shell: bash

        - name: Install & build eslint-remote-tester-repositories
          run: |
              pnpm install
              pnpm build
              rm -rf ./node_modules
          shell: bash
          working-directory: ./repositories

        - name: Cleanup
          run: rm -rf ./node_modules
          shell: bash

        - name: Install ci-runner dependencies
          run: pnpm install
          shell: bash
          working-directory: ./ci

        - name: Log ESLint packages
          run: pnpm list | grep eslint
          shell: bash
          working-directory: ./ci

        - name: Log plugin configuration
          run: pnpm log --config ./plugin-configs/${{ inputs.config }}.config.ts
          shell: bash
          working-directory: ./ci

        - uses: AriPerkkio/eslint-remote-tester-run-action@v4
          with:
              working-directory: ./ci
              issue-title: 'Weekly scheduled smoke test: ${{ inputs.config }}'
              eslint-remote-tester-config: plugin-configs/${{ inputs.config }}.config.ts
