name: Check for flaky integration tests

on: [workflow_dispatch]

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                node-version: [12.11, 14, 16]
                round: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
            - run: |
                  yarn install
                  yarn build
            - name: Integration test ${{ matrix.round }}
              run: yarn test:integration
              env:
                  NODE_NO_WARNINGS: 1
